[build]
    command = "npx ng build --prod"
    publish = "dist"

[build.environment]
    NODE_ENV = "production"

# ==============================================================================
# Headers
# ==============================================================================

# Security headers
# Use `Content-Security-Policy-Report-Only` header for safe and non-desctructive
#   CSP testing.
# @see https://securityheaders.com
# ==============================================================================

[[headers]]
    for = "/*"
    [headers.values]
        # Content-Security-Policy = ""
        # Content-Security-Policy-Report-Only = ""
        Referrer-Policy = "no-referrer-when-downgrade"
        Strict-Transport-Security = "max-age=31536000"
        X-Content-Type-Options = "nosniff"
        X-Frame-Options = "DENY"
        X-XSS-Protection = "1; mode=block"

# Performance headers
# ==============================================================================

# [[headers]]
#     for = "/favicon.ico"
#     [headers.values]
#         Cache-Control = "max-age=604800"    # access plus 1 week

# [[headers]]
#     for = "/assets/*"
#     [headers.values]
#         Cache-Control = "max-age=31536000" # access plus 1 year
